# Builds and serves Spartacus libraries on a local npm registry.
FROM node:18.17.1-alpine

EXPOSE 4873

# Installing git,python3,g++ for alpine image
RUN apk add --update --no-cache git python3 make g++ \
   && rm -rf /var/cache/apk/*

# Create a source directory to hold the Spartacus source code
WORKDIR /usr/app/spartacus

# Git clone the spartacus repository version 6.4.0 (ONLY)
RUN git clone -b '6.4.0' --single-branch --depth 1 https://github.com/SAP/spartacus ./

# Install the ts-node & verdaccio packages globally
RUN npm install -g ts-node@10 verdaccio@4 wait-on@7 @angular/cli

# Install the dependencies and build the libraries
# This process can take a few minutes to complete.
RUN npm install && npm run build:libs

# Copy some basic measmerize verdaccio credentials
# This prevents the expclit creation of a user via the 'npm adduser' commmand.
COPY ./tools/verdaccio-htpasswd ./scripts/install/htpasswd

# Copy the verdaccio config file.
# This file contains an important instruction that allows the service to listen on all interfaces (listen: 0.0.0.0).
COPY ./tools/verdaccio-config.yaml ./scripts/install/config.yaml

# Copy the publish typescript file.
# This file is a changed testing file only for publishing and exiting.
COPY ./tools/publish.ts ./tools/schematics/publish.ts

# Specify the credentials to be used, to publish to the local registry
# The _auth value is the base64 value of the measmerize credentials, specified above in the htpasswd file.
RUN touch ~/.npmrc && \
    echo "registry=http://localhost:4873/" >> ~/.npmrc && \
    echo "//localhost:4873/:_auth=\"bWVhc21lcml6ZTptZWFzbWVyaXpl\"" >> ~/.npmrc

# Create the entry point script without auto-publish the libraries
RUN touch start.sh && \
    echo "#!/bin/sh" >> start.sh && \
    echo "echo 'publish' | ts-node ./tools/schematics/testing" >> start.sh && \
    chmod +x start.sh

# Lets publish, and serve!
# Verdaccio's default port is: 4873
ENTRYPOINT ["./start.sh"]
