#
# Measmerize custom verdaccio config file to simplify the usage of the local builds and repo, via Docker.
#

# path to a directory with all packages
storage: ./storage

# path to a directory with plugins to include
plugins: ./plugins

web:
  title: Verdaccio

# This is important to allow connection from outside of Docker.
listen:
  0.0.0.0:4873

# Expected to contain the credentials for valid users.
auth:
  htpasswd:
    file: ./htpasswd

uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@spartacus/**':
    access: $all
    publish: $all
    unpublish: $all

server:
  keepAliveTimeout: 60

middlewares:
  audit:
    enabled: true

logs:
  - { type: stdout, format: pretty, level: http }
